# Generated by Django 4.2.6 on 2023-11-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categorie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
