# Generated by Django 4.2.6 on 2023-11-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_product_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='product',
            name='libelle',
        ),
        migrations.AddField(
            model_name='product',
            name='categorie',
            field=models.ManyToManyField(to='merchandise.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='libelle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
