# Generated by Django 4.2.5 on 2023-11-19 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='libelle',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categorie',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='merchandise.category'),
            preserve_default=False,
        ),
    ]
