# Generated by Django 4.2.5 on 2023-11-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0004_rename_categorie_product_categories_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
